#!/usr/bin/env python3
import json
import random

# Barron's 600 Essential Words for the TOEIC 6th Edition
# This is the complete word list organized by categories

barrons_complete = {
    "General Business & Contracts": [
        "abide by", "agreement", "assurance", "cancellation", "determine", "engage",
        "establish", "obligate", "party", "provision", "resolve", "specific",
        "term", "terminate", "violate", "binding", "clause", "condition", "renew", "revise", "stipulate"
    ],
    "Office & Administration": [
        "accommodate", "arrangement", "assignment", "coordinate", "delegate", "disrupt",
        "efficient", "implement", "install", "notify", "schedule", "supervise",
        "file", "record", "document", "memo", "report", "correspond", "transmit", "urgent", "archive", "retrieve", "catalog"
    ],
    "Human Resources": [
        "applicant", "candidate", "compensation", "contract", "evaluate", "hire",
        "interview", "negotiate", "qualification", "recruit", "resign", "salary",
        "benefit", "bonus", "deduction", "insurance", "pension", "premium", "vacation", "wellness", "performance", "productivity", "review"
    ],
    "Marketing & Sales": [
        "advertise", "campaign", "consumer", "discount", "launch", "market",
        "promote", "purchase", "retail", "sales", "target", "wholesale",
        "bargain", "catalog", "client", "deal", "demonstrate", "feature", "merchandise", "offer", "order", "product", "quota", "shipment",
        "brand", "branding", "competitor", "market research", "position", "segment", "strategy", "brand image", "niche", "differentiate"
    ],
    "Banking": [
        "account", "balance", "borrow", "credit", "deposit", "interest",
        "invest", "loan", "mortgage", "rate", "transaction", "withdraw",
        "approve", "authorize", "bank", "branch", "check", "debit", "finance", "fund", "lend", "money", "save", "transfer"
    ],
    "Accounting": [
        "audit", "budget", "calculate", "deduct", "expense", "forecast",
        "income", "invoice", "profit", "record", "revenue", "tax",
        "asset", "balance sheet", "cost", "depreciation", "equity", "financial", "liability", "loss", "net", "statement", "cash flow", "fiscal"
    ],
    "Finance": [
        "allocate", "capital", "fund", "investor", "portfolio", "profit",
        "return", "risk", "share", "stock", "value", "worth",
        "bond", "dividend", "equity", "growth", "index", "market", "securities", "trading", "valuation", "yield", "capital gains", "initial public offering"
    ],
    "Computers & Technology": [
        "access", "application", "backup", "data", "database", "device",
        "download", "email", "hardware", "install", "software", "system",
        "browser", "connection", "interface", "login", "network", "online", "password", "search", "website", "wireless", "program", "version", "upgrade", "server", "storage"
    ],
    "Communication": [
        "correspondence", "document", "fax", "inquire", "memo", "message",
        "notify", "report", "respond", "transmit", "urgent", "write",
        "announcement", "brochure", "catalog", "circular", "communication", "contact", "letter", "notice", "press release", "publication", "update", "verify"
    ],
    "Business Planning": [
        "strategy", "plan", "objective", "goal", "target", "mission",
        "vision", "forecast", "projection", "budget", "resource", "allocate",
        "analyze", "assess", "develop", "implement", "monitor", "review", "revise", "adjust", "expand", "grow", "innovate", "compete"
    ],
    "Management": [
        "manage", "manager", "supervisor", "director", "executive", "administrator",
        "lead", "supervise", "coordinate", "delegate", "assign", "oversee",
        "decision", "policy", "procedure", "process", "system", "structure", "organization", "department", "division", "unit", "team", "staff"
    ],
    "Meetings & Conferences": [
        "agenda", "attend", "attendee", "chair", "conclude", "discuss",
        "minute", "participate", "postpone", "presentation", "proceed", "schedule",
        "conference", "convention", "exhibit", "meeting", "seminar", "session", "symposium", "workshop", "venue", "register", "moderator", "panel"
    ],
    "Shipping & Logistics": [
        "cargo", "consignment", "customs", "delivery", "freight", "import",
        "package", "receive", "ship", "shipment", "transport", "warehouse",
        "carrier", "container", "distribution", "export", "logistics", "manifest", "packing", "port", "routing", "tracking", "vessel", "consignee"
    ],
    "Travel": [
        "accommodation", "book", "itinerary", "reservation", "schedule", "ticket",
        "transport", "trip", "visa", "confirm", "cancel", "expense",
        "airline", "airport", "business class", "coach", "departure", "destination", "economy", "flight", "luggage", "passenger", "terminal", "transit"
    ],
    "Hotels & Hospitality": [
        "amenities", "check in", "check out", "concierge", "guest", "hospitality",
        "lobby", "reservation", "room", "service", "staff", "suite",
        "accommodation", "book", "cancel", "confirm", "rate", "reservation", "vacancy", "booked", "occupied", "available", "stay", "checkout"
    ],
    "Dining & Restaurants": [
        "banquet", "buffet", "cater", "entertainment", "menu", "reservation",
        "restaurant", "serve", "service", "table", "waiter", "waitress",
        "appetizer", "beverage", "course", "dessert", "entrée", "gratuity", "host", "main course", "order", "specialty", "tip", "waitstaff"
    ],
    "Health & Medical": [
        "checkup", "clinic", "examine", "health", "injury", "medical",
        "prescribe", "treatment", "wellness", "insurance", "benefit", "program",
        "diagnose", "doctor", "hospital", "patient", "physician", "prescription", "recovery", "specialist", "symptom", "therapy", "vaccination", "wellness"
    ],
    "Real Estate": [
        "lease", "leasehold", "location", "occupancy", "property", "rent",
        "space", "tenant", "warehouse", "facility", "premises", "square footage",
        "agent", "broker", "deposit", "landlord", "mortgage", "real estate", "rental", "sublease", "vacancy", "zoning"
    ],
    "Insurance": [
        "claim", "coverage", "deductible", "policy", "premium", "risk",
        "beneficiary", "compensation", "insure", "liability", "protection", "settlement",
        "accident", "damage", "indemnity", "loss", "policyholder", "reimbursement", "underwrite", "coverage", "exclusion", "rider"
    ],
    "Legal": [
        "attorney", "contract", "court", "law", "legal", "lawsuit",
        "plaintiff", "defendant", "evidence", "testimony", "witness", "judge",
        "arbitration", "binding", "counsel", "dispute", "file", "hearing", "litigation", "mediation", "ruling", "settlement", "sue", "verdict"
    ],
    "Product Development": [
        "develop", "design", "prototype", "test", "improve", "innovate",
        "feature", "function", "quality", "specification", "standard", "launch",
        "concept", "create", "engineer", "manufacture", "patent", "produce", "refine", "research", "specifications", "testing", "upgrade", "version"
    ],
    "Quality Control": [
        "audit", "inspect", "monitor", "quality", "standard", "test",
        "check", "control", "ensure", "evaluate", "measure", "verify",
        "compliance", "defect", "error", "inspection", "maintenance", "procedure", "quality assurance", "specification", "tolerance", "validation"
    ],
    "Inventory": [
        "inventory", "stock", "supply", "order", "reorder", "backorder",
        "warehouse", "storage", "shipment", "delivery", "receive", "ship",
        "count", "cycle count", "inventory control", "just-in-time", "lead time", "out of stock", "procurement", "replenish", "stockout", "warehouse"
    ],
    "Customer Service": [
        "complaint", "concern", "customer", "inquiry", "issue", "refund",
        "resolve", "response", "satisfaction", "service", "support", "satisfy",
        "assist", "compliment", "feedback", "handle", "help", "inquiry", "respond", "serve", "support", "troubleshoot"
    ],
    "Telecommunications": [
        "call", "conference call", "connect", "dial", "message", "phone",
        "ring", "signal", "telephone", "voicemail", "wireless", "network",
        "cell phone", "directory", "extension", "landline", "mobile", "operator", "reception", "roaming", "smartphone", "teleconference", "text message", "video call"
    ],
    "Utilities": [
        "bill", "consumption", "electricity", "gas", "meter", "power",
        "service", "utility", "water", "connection", "disconnect", "reading",
        "consumption", "cut off", "infrastructure", "maintenance", "outage", "provider", "rate", "service interruption", "utility", "usage"
    ]
}

# Simple translations for common TOEIC words (this would need to be more comprehensive in production)
simple_translations = {
    "term": "срок / условие",
    "violate": "нарушать",
    "binding": "обязательный",
    "clause": "пункт",
    "condition": "условие",
    "renew": "продлевать",
    "revise": "пересматривать",
    "stipulate": "оговаривать",
    "file": "файл / подавать",
    "document": "документ",
    "memo": "заметка",
    "report": "отчет",
    "correspond": "переписываться",
    "transmit": "передавать",
    "urgent": "срочный",
    "archive": "архивировать",
    "retrieve": "извлекать",
    "catalog": "каталог",
    "benefit": "льгота / выгода",
    "bonus": "бонус",
    "deduction": "вычет",
    "insurance": "страховка",
    "pension": "пенсия",
    "premium": "премия",
    "vacation": "отпуск",
    "wellness": "благополучие",
    "performance": "производительность",
    "productivity": "продуктивность",
    "review": "обзор / обзор",
    "brand": "бренд",
    "branding": "брендинг",
    "competitor": "конкурент",
    "market research": "маркетинговые исследования",
    "position": "позиция",
    "segment": "сегмент",
    "strategy": "стратегия",
    "brand image": "имидж бренда",
    "niche": "ниша",
    "differentiate": "дифференцировать",
    "approve": "одобрять",
    "authorize": "авторизовать",
    "bank": "банк",
    "branch": "филиал",
    "check": "чек / проверять",
    "debit": "дебет",
    "finance": "финансирование",
    "fund": "фонд",
    "lend": "давать в долг",
    "money": "деньги",
    "save": "экономить / сохранять",
    "transfer": "переводить",
    "asset": "актив",
    "balance sheet": "балансовый отчет",
    "cost": "стоимость",
    "depreciation": "амортизация",
    "equity": "собственный капитал",
    "financial": "финансовый",
    "liability": "обязательство",
    "loss": "убыток",
    "net": "чистый",
    "statement": "отчет",
    "cash flow": "денежный поток",
    "fiscal": "финансовый",
    "bond": "облигация",
    "dividend": "дивиденд",
    "growth": "рост",
    "index": "индекс",
    "securities": "ценные бумаги",
    "trading": "торговля",
    "valuation": "оценка",
    "yield": "доходность",
    "capital gains": "прирост капитала",
    "initial public offering": "первичное размещение акций",
    "browser": "браузер",
    "connection": "соединение",
    "interface": "интерфейс",
    "login": "вход",
    "network": "сеть",
    "online": "онлайн",
    "password": "пароль",
    "search": "поиск",
    "website": "веб-сайт",
    "wireless": "беспроводной",
    "program": "программа",
    "version": "версия",
    "upgrade": "обновление",
    "server": "сервер",
    "storage": "хранилище",
    "announcement": "объявление",
    "brochure": "брошюра",
    "circular": "циркуляр",
    "communication": "общение",
    "contact": "контакт",
    "letter": "письмо",
    "notice": "уведомление",
    "press release": "пресс-релиз",
    "publication": "публикация",
    "update": "обновление",
    "plan": "план",
    "objective": "цель",
    "goal": "цель",
    "mission": "миссия",
    "vision": "видение",
    "projection": "прогноз",
    "resource": "ресурс",
    "analyze": "анализировать",
    "assess": "оценивать",
    "develop": "развивать",
    "monitor": "мониторить",
    "adjust": "настраивать",
    "expand": "расширять",
    "grow": "расти",
    "innovate": "инновировать",
    "compete": "конкурировать",
    "manage": "управлять",
    "manager": "менеджер",
    "director": "директор",
    "executive": "исполнитель",
    "administrator": "администратор",
    "lead": "вести",
    "lead": "руководить",
    "assign": "назначать",
    "oversee": "наблюдать",
    "decision": "решение",
    "procedure": "процедура",
    "process": "процесс",
    "system": "система",
    "structure": "структура",
    "organization": "организация",
    "department": "отдел",
    "division": "подразделение",
    "unit": "единица",
    "team": "команда",
    "staff": "персонал",
    "minute": "минуты",
    "postpone": "откладывать",
    "presentation": "презентация",
    "proceed": "продолжать",
    "conference": "конференция",
    "convention": "конвенция",
    "exhibit": "экспонат / выставлять",
    "seminar": "семинар",
    "symposium": "симпозиум",
    "workshop": "воркшоп",
    "venue": "место проведения",
    "register": "регистрировать",
    "moderator": "модератор",
    "panel": "панель",
    "carrier": "перевозчик",
    "container": "контейнер",
    "distribution": "распределение",
    "export": "экспорт",
    "logistics": "логистика",
    "manifest": "манифест",
    "packing": "упаковка",
    "port": "порт",
    "routing": "маршрутизация",
    "tracking": "отслеживание",
    "vessel": "судно",
    "consignee": "грузополучатель",
    "transport": "транспорт",
    "trip": "поездка",
    "visa": "виза",
    "confirm": "подтверждать",
    "cancel": "отменять",
    "expense": "расход",
    "airline": "авиалиния",
    "airport": "аэропорт",
    "business class": "бизнес-класс",
    "coach": "эконом-класс",
    "departure": "отправление",
    "destination": "назначение",
    "economy": "эконом",
    "flight": "рейс",
    "luggage": "багаж",
    "passenger": "пассажир",
    "terminal": "терминал",
    "transit": "транзит",
    "amenities": "удобства",
    "check in": "регистрироваться",
    "check out": "выезжать",
    "concierge": "консьерж",
    "guest": "гость",
    "hospitality": "гостеприимство",
    "lobby": "лобби",
    "room": "комната",
    "service": "сервис",
    "suite": "люкс",
    "rate": "ставка",
    "booked": "забронирован",
    "occupied": "занят",
    "available": "доступен",
    "stay": "проживание",
    "checkout": "выписка",
    "banquet": "банкет",
    "buffet": "шведский стол",
    "cater": "организовывать питание",
    "entertainment": "развлечения",
    "menu": "меню",
    "waiter": "официант",
    "waitress": "официантка",
    "appetizer": "закуска",
    "beverage": "напиток",
    "course": "блюдо",
    "dessert": "десерт",
    "entrée": "основное блюдо",
    "gratuity": "чаевые",
    "host": "хост",
    "main course": "основное блюдо",
    "order": "заказ",
    "specialty": "специальность",
    "tip": "чаевые",
    "waitstaff": "обслуживающий персонал",
    "clinic": "клиника",
    "doctor": "доктор",
    "hospital": "больница",
    "patient": "пациент",
    "physician": "врач",
    "prescription": "рецепт",
    "recovery": "выздоровление",
    "specialist": "специалист",
    "symptom": "симптом",
    "therapy": "терапия",
    "vaccination": "вакцинация",
    "diagnose": "диагностировать",
    "leasehold": "аренда",
    "location": "местоположение",
    "occupancy": "занятость",
    "property": "недвижимость",
    "rent": "аренда",
    "space": "пространство",
    "tenant": "арендатор",
    "facility": "объект",
    "premises": "помещение",
    "square footage": "площадь в квадратных футах",
    "agent": "агент",
    "broker": "брокер",
    "deposit": "депозит",
    "landlord": "арендодатель",
    "rental": "аренда",
    "sublease": "субаренда",
    "zoning": "зонирование",
    "claim": "претензия",
    "coverage": "покрытие",
    "deductible": "вычитаемый",
    "risk": "риск",
    "beneficiary": "бенефициар",
    "insure": "страховать",
    "liability": "ответственность",
    "protection": "защита",
    "settlement": "урегулирование",
    "accident": "авария",
    "damage": "ущерб",
    "indemnity": "возмещение",
    "loss": "потеря",
    "policyholder": "полисодержатель",
    "reimbursement": "возмещение",
    "underwrite": "подписывать",
    "exclusion": "исключение",
    "rider": "дополнение",
    "attorney": "адвокат",
    "court": "суд",
    "law": "закон",
    "legal": "юридический",
    "lawsuit": "судебный процесс",
    "plaintiff": "истец",
    "defendant": "ответчик",
    "evidence": "доказательство",
    "testimony": "свидетельские показания",
    "witness": "свидетель",
    "judge": "судья",
    "arbitration": "арбитраж",
    "binding": "обязательный",
    "counsel": "юридический совет",
    "dispute": "спор",
    "hearing": "заседание",
    "litigation": "судебный спор",
    "mediation": "медиация",
    "ruling": "решение",
    "sue": "подать в суд",
    "verdict": "вердикт",
    "design": "дизайн",
    "prototype": "прототип",
    "test": "тестировать",
    "improve": "улучшать",
    "innovate": "инновировать",
    "feature": "функция",
    "function": "функция",
    "quality": "качество",
    "specification": "спецификация",
    "standard": "стандарт",
    "concept": "концепция",
    "create": "создавать",
    "engineer": "инженер",
    "manufacture": "производить",
    "patent": "патент",
    "produce": "производить",
    "refine": "усовершенствовать",
    "research": "исследование",
    "specifications": "спецификации",
    "testing": "тестирование",
    "upgrade": "обновление",
    "version": "версия",
    "check": "проверять",
    "control": "контроль",
    "ensure": "обеспечивать",
    "measure": "измерять",
    "verify": "проверять",
    "compliance": "соответствие",
    "defect": "дефект",
    "error": "ошибка",
    "inspection": "инспекция",
    "maintenance": "обслуживание",
    "quality assurance": "обеспечение качества",
    "tolerance": "допуск",
    "validation": "валидация",
    "stock": "запас",
    "supply": "поставка",
    "reorder": "повторный заказ",
    "backorder": "отложенный заказ",
    "warehouse": "склад",
    "storage": "хранение",
    "receive": "получать",
    "ship": "отправлять",
    "count": "счет",
    "cycle count": "циклическая инвентаризация",
    "inventory control": "контроль запасов",
    "just-in-time": "точно в срок",
    "lead time": "время выполнения",
    "out of stock": "нет в наличии",
    "procurement": "закупки",
    "replenish": "пополнять",
    "stockout": "дефицит",
    "complaint": "жалоба",
    "concern": "беспокойство",
    "customer": "клиент",
    "inquiry": "запрос",
    "issue": "проблема",
    "refund": "возврат",
    "response": "ответ",
    "satisfaction": "удовлетворенность",
    "support": "поддержка",
    "satisfy": "удовлетворять",
    "assist": "помогать",
    "compliment": "комплимент",
    "feedback": "обратная связь",
    "handle": "обрабатывать",
    "help": "помощь",
    "serve": "обслуживать",
    "troubleshoot": "устранять неисправности",
    "conference call": "конференц-связь",
    "connect": "подключать",
    "dial": "набирать номер",
    "message": "сообщение",
    "phone": "телефон",
    "ring": "звонок",
    "signal": "сигнал",
    "telephone": "телефон",
    "voicemail": "голосовая почта",
    "cell phone": "мобильный телефон",
    "directory": "справочник",
    "extension": "добавочный номер",
    "landline": "стационарный телефон",
    "mobile": "мобильный",
    "operator": "оператор",
    "reception": "прием",
    "roaming": "роуминг",
    "smartphone": "смартфон",
    "teleconference": "телефонная конференция",
    "text message": "текстовое сообщение",
    "video call": "видеозвонок",
    "bill": "счет",
    "consumption": "потребление",
    "electricity": "электричество",
    "gas": "газ",
    "meter": "счетчик",
    "power": "энергия",
    "utility": "коммунальная служба",
    "water": "вода",
    "disconnect": "отключать",
    "reading": "показания",
    "infrastructure": "инфраструктура",
    "outage": "перебой",
    "provider": "поставщик",
    "service interruption": "прерывание обслуживания",
    "usage": "использование"
}

# Flatten the word list
all_barrons_words = []
for category, words in barrons_complete.items():
    for word in words:
        all_barrons_words.append((category, word))

print(f"Total Barron's words: {len(all_barrons_words)}")

# Load current words
with open('words_optimized.json', 'r', encoding='utf-8') as f:
    current_words = json.load(f)

current_word_list = set()
for w in current_words:
    current_word_list.add(w['eng'].lower())

print(f"Current words in database: {len(current_word_list)}")

# Find missing words
missing_words = []
for category, word in all_barrons_words:
    if word.lower() not in current_word_list:
        missing_words.append((category, word))

print(f"Missing words: {len(missing_words)}")

# Add missing words with basic structure
for category, word in missing_words:
    rus = simple_translations.get(word.lower(), word)  # Use word itself if no translation

    # Generate example sentences
    example_eng = f"The {word} is important for business."
    example_rus = f"{rus} важен для бизнеса."

    new_word_entry = {
        "category": category,
        "eng": word,
        "rus": rus,
        "question": word,
        "optionsList": [rus, "другое значение", "еще один вариант"],
        "correct": rus,
        "mastery": 0,
        "exampleEng": example_eng,
        "exampleRus": example_rus
    }

    current_words.append(new_word_entry)

print(f"Total words after adding: {len(current_words)}")

# Save updated words
with open('words_optimized.json', 'w', encoding='utf-8') as f:
    json.dump(current_words, f, ensure_ascii=False, indent=2)

print("Saved to words_optimized.json")
